export default function BookPhoto({author, book}) {
    let coverImageUrl = book.profilePhoto;
    if (! coverImageUrl) {
        return null
        // coverImageUrl = `https://storage.googleapis.com/covers.data.robotbookclub.com/empty-book.png`
    }

    // Get altName from the cover image URL
    let altName;
    if (coverImageUrl.includes("DALLE")) {
        let imageName = coverImageUrl.split("/").pop()
        if (!imageName) {
            altName = `${book.name} Cover`
        } else {
            altName = `Image generated by OpenAI DALL-E with the following image name (date and prompt): ${imageName}`
        }
    } else {
        altName = `${book.name} Cover`
    }

    return (
        <img className="h-52 inline-block ml-2 pl-5" src={coverImageUrl} alt={altName} />
    )
}